name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_run:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    workflows: ["Bump version in git"]
    types:
      - completed

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get version tag
        id: version_tag
        run: |
          git fetch --tags --force # Retrieve annotated tags. THIS TRICK REALLY HELPS
          echo "::set-output name=VERSION::$(git for-each-ref refs/tags --sort=-taggerdate --format='%(refname:short)' --count=1| sed -e 's/^v//')"

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@2a6fbda6d8bd6fe40f8b36c71fca20ffc286129e

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@7c79b598eaa33458e78e8d0d71e0a9c217dd92af
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build the Docker image
        run: make build VERSION=${{ steps.version_tag.outputs.VERSION }}
      - name: push the image image
        if: github.event_name != 'pull_request'
        run: make docker-push VERSION=${{ steps.version_tag.outputs.VERSION }}
